World=None
Server=127.0.0.1:1115
usenewui=1

SteamGatewayUrl=http://127.0.0.1:1116/rest/auth/session/create

[Environment]
Sku=2

[GameSettings]
FirstPerson=1

[Paths]
PathScripts=.\Resources\Scripts\
PathUiModules=.\UI\UiModules\

[SoeData]
FilesystemRoot=.

[Libraries]
#For Deep
GraphicsDataPath=GraphicsData

[AssetDelivery]
IndirectThreadCount=10
DirectThreadCount=3
DirectEnabled=1
IndirectEnabled=1
Paths=.\Resources\;.\CommonData\;.\GraphicsData\
AdditionalPaths=.\CommonData\;.\GraphicsData\
PackFileDir=.\Resources\Assets
PackType=1

[INGAMEPURCHASE]
UramPlatform=account
UramCert=.\Resources\Security\soe-ssl-certs.pem
CasPlatform=auth
Theme=h1z1xxInGame
CasCert=.\Resources\Security\soe-ssl-certs.pem
AutoInitializeSystemSupport=1
MarketingDataPath=.\Resources\Marketing\
SoeAuthTicketUrl=http://127.0.0.1:1116/rest/client/session/create
InternalWebForPsg=0

[LoadingScreen]
LoadingScreenMusicId=16313

[CrashReporter]
Address=
NoUploadFromInit=1
#IncludeIndirectMemory=1

[WebResources]
GameCrashUrl=http://127.0.0.1:1116/king-of-the-kill/game-error?code=G

[WallOfData]
Collecting=0

[Voice]
BaseURI=hzp.vivox.com

[Help]
PetitionUri=http://127.0.0.1:1116%s.custhelp.com/app/answers/list/p/5833/c/5933

[LodBins]
Character=5,20,50
Vehicle=4,16,40

[Logging]
Address=
LocalLogLevel=0

[InfiniteLoopMonitor]
TimeoutSeconds=60

[CommandQueue]
motd_uri=http://127.0.0.1:1116/
cb_uri=http://127.0.0.1:1116/
eula_uri=http://127.0.0.1:1116/
alert_logonly=1

[LaunchTelemetry]
Url=http://127.0.0.1:1116/h1z1xx/live/
