World=None
Server=Lvshaa-liv-l02.h1z1.net:20042;Lvshaa-liv-l02.h1z1.net:20043;Lvshaa-liv-l02.h1z1.net:20044;Lvshaa-liv-l02.h1z1.net:20045
usenewui=1

SteamGatewayUrl=https://steamgateway.daybreakgames.com/rest/auth/session/create

[Environment]
Sku=2

[GameSettings]
FirstPerson=1

[Paths]
PathScripts=.\Resources\Scripts\
PathUiModules=.\UI\UiModules\

[SoeData]
FilesystemRoot=.

[Libraries]
#For Deep
GraphicsDataPath=GraphicsData

[AssetDelivery]
IndirectThreadCount=10
DirectThreadCount=3
DirectEnabled=1
IndirectEnabled=1
Paths=.\Resources\;.\CommonData\;.\GraphicsData\
AdditionalPaths=.\CommonData\;.\GraphicsData\
PackFileDir=.\Resources\Assets
PackType=1

[INGAMEPURCHASE]
UramPlatform=account
UramCert=.\Resources\Security\soe-ssl-certs.pem
CasPlatform=auth
Theme=h1z1xxInGame
CasCert=.\Resources\Security\soe-ssl-certs.pem
AutoInitializeSystemSupport=1
MarketingDataPath=.\Resources\Marketing\
SoeAuthTicketUrl=https://partner.soe.platformpublishing.com/rest/client/session/create
InternalWebForPsg=0

[LoadingScreen]
LoadingScreenMusicId=16313

[CrashReporter]
Address=recap.daybreakgames.com:15081
NoUploadFromInit=1
#IncludeIndirectMemory=1

[WebResources]
GameCrashUrl=https://www.h1z1.com/king-of-the-kill/game-error?code=G

[WallOfData]
Collecting=0

[Voice]
BaseURI=hzp.vivox.com

[Help]
PetitionUri=http://soe-%s.custhelp.com/app/answers/list/p/5833/c/5933

[LodBins]
Character=5,20,50
Vehicle=4,16,40

[Logging]
Address=
LocalLogLevel=0

[InfiniteLoopMonitor]
TimeoutSeconds=60

[CommandQueue]
motd_uri=http://assets-cdn.daybreakgames.com/
cb_uri=http://assets-cdn.daybreakgames.com/
eula_uri=http://assets-cdn.daybreakgames.com/
alert_logonly=1

[LaunchTelemetry]
Url=https://lpj.daybreakgames.com/h1z1xx/live/
